---
- name: provision for grafana server
  hosts: apps
  become: yes
  roles:
    - grafana


# ---
# - name: provision for grafana server
#   hosts: grafana
#   become: yes
#   roles:
#     - grafana