---
- name: install prometheus
  hosts: target_hosts  # Ganti dengan grup host yang sesuai
  become: true         # Mengaktifkan hak superuser (sudo)
  tasks:
    - name: Create Prometheus user
      ansible.builtin.user:
        name: prometheus
        state: present

- name: Download Prometheus
  ansible.builtin.get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.33.1/prometheus-2.33.1.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  ansible.builtin.unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt
        remote_src: yes
        creates: /opt/prometheus-2.33.1.linux-amd64  # Ganti dengan versi yang diunduh

- name: Create a symlink
  ansible.builtin.file:
        src: /opt/prometheus-2.33.1.linux-amd64/prometheus
        dest: /usr/local/bin/prometheus
        state: link

- name: Create Prometheus configuration directory
  ansible.builtin.file:
        path: /etc/prometheus
        state: directory

- name: Copy Prometheus configuration file
  ansible.builtin.copy:
        src: /opt/prometheus-2.33.1.linux-amd64/prometheus.yml
        dest: /etc/prometheus/prometheus.yml

- name: Configure systemd service
  ansible.builtin.copy:
        content: |
          [Unit]
          Description=Prometheus
          After=network.target

          [Service]
          User=prometheus
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus/data

          [Install]
          WantedBy=default.target
        dest: /etc/systemd/system/prometheus.service

- name: Start and enable Prometheus service
  ansible.builtin.systemd:
        name: prometheus
        enabled: yes
        state: started
